### ISSUE TITLE
AssertionError: action space does not inherit from `gymnasium.spaces.Space`, actual type: <class 'gym.spaces.box.Box'>

### ISSUE THREAD

**Issue by 623637719** [liuzuxin/OSRL#8] opened 2023-08-14 15:39 UTC
The configuration of my computer is as follows
![image](https://github.com/liuzuxin/OSRL/assets/111236370/e188e513-1f70-4ffb-bad2-b467a0093abc)

I directly ran your train_cdt.py file without any modification, and the following error occurred. May you help me to solve it？
![image](https://github.com/liuzuxin/OSRL/assets/111236370/9ea1831b-ba7d-442d-bfaf-00117725f214)

**Comment by liuzuxin** [comment] 2023-08-14 17:08
It seems that the BulletSafetyGym version is out-of-date. The old BulleSafetyGym that uses OpenAI gym API doesn't support the new Gymnasium API. Could you try reinstalling the BulletSafetyGym package from [here](https://github.com/liuzuxin/Bullet-Safety-Gym/tree/master)?

**Comment by 623637719** [comment] 2023-08-16 15:34
Thank you for your answer!
But to run your code I already reinstalled the gym,Is there any other way to solve this problem?
![image](https://github.com/liuzuxin/OSRL/assets/111236370/09f221bc-b01b-47a5-9111-27fabf629e03)


> It seems that the BulletSafetyGym version is out-of-date. The old BulleSafetyGym that uses OpenAI gym API doesn't support the new Gymnasium API. Could you try reinstalling the BulletSafetyGym package from [here](https://github.com/liuzuxin/Bullet-Safety-Gym/tree/master)?

**Comment by liuzuxin** [comment] 2023-08-17 02:26
This is strange, could you provide the full scripts for reproducing the error in the first image and let me know which Python version are you using? Also, you can try build from source:

```
git clone https://github.com/liuzuxin/Bullet-Safety-Gym.git

cd Bullet-Safety-Gym

pip install -e .
``` 

I haven't tested all the packages in Windows but at least this `bullet-safety-gym` should work.

**Comment by liuzuxin** [comment] 2023-08-21 05:38
> After opening your project I directly right click on the train_cdt.py to run the code，

I am not sure whether you can directly run the code via this IDE, since this IDE (pycharm?) may not be able to automatically choose the CDT conda Python environment to run the code. You should probably check whether your IDE's python environment is correctly configured: https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html

The second issue seems like the `setuptools` package is too new, you may try to downgrade this `setuptools` package to `65.x` and see whether you can install it.

Unfortunately, I don't have a Windows machine at hand so I am not able to test these packages on Windows, but at least for Ubuntu 20.04 and 22.04, the packages can be installed and run smoothly from my side.

**Comment by 623637719** [comment] 2023-08-23 09:27
> > After opening your project I directly right click on the train_cdt.py to run the code，
> 
> I am not sure whether you can directly run the code via this IDE, since this IDE (pycharm?) may not be able to automatically choose the CDT conda Python environment to run the code. You should probably check whether your IDE's python environment is correctly configured: https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html
> 
> The second issue seems like the `setuptools` package is too new, you may try to downgrade this `setuptools` package to `65.x` and see whether you can install it.
> 
> Unfortunately, I don't have a Windows machine at hand so I am not able to test these packages on Windows, but at least for Ubuntu 20.04 and 22.04, the packages can be installed and run smoothly from my side.

Yest,it's pycharm,and I'm sure that my IDE's python environment is correctly configured:
![image](https://github.com/liuzuxin/OSRL/assets/111236370/d6ade0ae-3a2d-46e9-95be-5679d2a72788)

I tried to downgrade this setuptools package to 65.0 and I still can't install it.
![f5aa9599e540bf542476e2ab57062d5](https://github.com/liuzuxin/OSRL/assets/111236370/d2a9824e-91d8-455c-a836-74324dcfc3a2)

I tried to debug train_cdt.py and I found that every time when the code ran to line 54 ,errors appeared,as the picture below 
![image](https://github.com/liuzuxin/OSRL/assets/111236370/315ea567-27a2-4483-afff-f937479cb84e)

![image](https://github.com/liuzuxin/OSRL/assets/111236370/c4a79e74-d791-4e53-b3ac-9e6f244c80b7)

**Comment by 623637719** [comment] 2023-08-23 09:36
> > After opening your project I directly right click on the train_cdt.py to run the code，
> 
> I am not sure whether you can directly run the code via this IDE, since this IDE (pycharm?) may not be able to automatically choose the CDT conda Python environment to run the code. You should probably check whether your IDE's python environment is correctly configured: https://www.jetbrains.com/help/pycharm/configuring-python-interpreter.html
> 
> The second issue seems like the `setuptools` package is too new, you may try to downgrade this `setuptools` package to `65.x` and see whether you can install it.
> 
> Unfortunately, I don't have a Windows machine at hand so I am not able to test these packages on Windows, but at least for Ubuntu 20.04 and 22.04, the packages can be installed and run smoothly from my side.

oh,it's very strange that the error I mentioned at the beginning disappeared:"AssertionError: action space does not inherit from gymnasium.spaces.Space, actual type: <class 'gym.spaces.box.Box'>" ，but I still can't run the code successfully.

**Comment by liuzuxin** [comment] 2023-08-30 01:45
Thanks for providing these screenshots. 
![image](https://github.com/liuzuxin/OSRL/assets/17945444/f3ccde59-67f2-4500-8c60-ed7231b701b1)

The error you're encountering above is due to the fact that Python is trying to read a file with the 'gbk' codec (common in Chinese versions of Windows) and is finding characters it can't decode. This issue often arises when handling non-ASCII characters. As I don't have a Chinese version of Windows at hand, I can not reproduce this error and fix it, but I believe there should be ways online to fix it. A simple fix is simply comment our the `long_description` part in [setup.py](https://github.com/liuzuxin/Bullet-Safety-Gym/blob/master/setup.py#L44) when installing the package.

I suspect that the errors you were encountering are mainly because of the unsuccessful installation of `bullet-safet-gym`. If you still encounter errors, please provide the running commands, and paste the error logs here for further diagnosis.

**Comment by 623637719** [comment] 2023-09-04 16:51
> Thanks for providing these screenshots. ![image](https://user-images.githubusercontent.com/17945444/264202640-f3ccde59-67f2-4500-8c60-ed7231b701b1.png)
> 
> The error you're encountering above is due to the fact that Python is trying to read a file with the 'gbk' codec (common in Chinese versions of Windows) and is finding characters it can't decode. This issue often arises when handling non-ASCII characters. As I don't have a Chinese version of Windows at hand, I can not reproduce this error and fix it, but I believe there should be ways online to fix it. A simple fix is simply comment our the `long_description` part in [setup.py](https://github.com/liuzuxin/Bullet-Safety-Gym/blob/master/setup.py#L44) when installing the package.
> 
> I suspect that the errors you were encountering are mainly because of the unsuccessful installation of `bullet-safet-gym`. If you still encounter errors, please provide the running commands, and paste the error logs here for further diagnosis.

Terribly，I do comment  the long_description part in setup.py when installing the package,but still failed.
![image](https://github.com/liuzuxin/OSRL/assets/111236370/a3c25e6d-3800-4ec4-9a9a-71a0a8cf5f49)
![image](https://github.com/liuzuxin/OSRL/assets/111236370/2cb16a0d-dfd8-42ee-a3d4-af0b82b2e48e)

**Comment by liuzuxin** [comment] 2023-09-04 22:11
You also need to comment out these three lines since the errors come from here: https://github.com/liuzuxin/Bullet-Safety-Gym/blob/6f9f480a096b9fc2b9991e994fdea9ef9fb776bb/setup.py#L8-L10

**Comment by 623637719** [comment] 2023-09-05 03:25
> You also need to comment out these three lines since the errors come from here: https://github.com/liuzuxin/Bullet-Safety-Gym/blob/6f9f480a096b9fc2b9991e994fdea9ef9fb776bb/setup.py#L8-L10

Thank you very much！You are right！I successfully install it！

**Comment by liuzuxin** [comment] 2023-09-06 23:22
You are welcome. If there is no further questions, I am closing this issue now.

**Closed by liuzuxin** 2023-09-06 23:22 UTC
